-
  name: "Deploy a Webpage with Database"
  hosts: all
  become: yes
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt: update_cache=yes

    - name: "Install MySql dependencies"
      apt: name={{ item }} state=present
      loop:
       - python3
       - python3-pip
       - python3-mysqldb

    - name: "Install MySQL database"
      apt: name={{ item }} state=present
      loop:
       - mysql-server
       - mysql-client

    - name: "Start Mysql Service"
      service: name='mysql' state=started enabled=yes

    - name: "Create Database"
      mysql_db: name='sample_database' login_unix_socket=/var/run/mysqld/mysqld.sock state=present

    - name: "Create Database User"
      mysql_user: name='sample_user' password='Passw0rd' priv='*.*:ALL' host='%' login_unix_socket=/var/run/mysqld/mysqld.sock state=present

    - name: "Copy SQL query"
      copy: src=sample.sql dest=/tmp/sample.sql

    - name: "Create Table and Add data to table"
      mysql_db: name='sample_database' state=import target=/tmp/sample.sql login_user='sample_user' login_password='Passw0rd'

    - name: "Install Webpage dependencies"
      pip: name='{{ item }}' state=present
      loop:
       - flask
       - flask-mysql

    - name: "Copy web code"
      copy: src=app.py dest=/opt/app.py

    - name: "Start Web-application"
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &